### ISSUE TITLE
Яндекс.Практикум:Код-ревью

### ISSUE THREAD

**Issue by talantbekov123** [i-c-winner/i-c-winner.github.io#5]
Добрый день, хорошая работа. К сожалению текущая реализация содержит ряд недостатков, не позволяющих мне засчитать работу на данной итерации.

**Надо исправить**
- Прошу добавить ссылку на проект в readme.md
- В репозитории не указали версии. По умолчанию, команда git push не отправляет теги на удалённые сервера. После создания тегов нужно отправлять явно на удалённый сервер. Процесс аналогичен отправке веток — достаточно выполнить команду `git push origin <tagname>` или `git push origin --tags`. Подробнее можно ознакомиться [тут](https://git-scm.com/book/ru/v2/%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D1%8B-Git-%D0%A0%D0%B0%D0%B1%D0%BE%D1%82%D0%B0-%D1%81-%D0%BC%D0%B5%D1%82%D0%BA%D0%B0%D0%BC%D0%B8#r_git_tagging)
- Имя:
Нужно исправить: Не проходят валидацию корректные двойные имена Денис-Иван
После исправления проверьте следующие кейсы:
```
Позитивные:
Денис
Денис-Иван
Негативные:
Денис- (дефис, нет двойного имени, допустимо либо Денис, либо Денис-Иван)
Денис-ловеркейс (второе имя должно быть с заглавной буквы)
денис-Ян (первое имя должно быть с заглавной буквы)
Денис-Иvан (имя состоит только из кирилицы)
```

**Можно лучше**
- Дополнительно включить в сет регулярки точки, подчеркивания. Не проходит валидная почты с использованием точки. Например: yandex.staff@gmail.com, alex.lion@gmail.com, test.test@test.gmail.com, best-email@yandex.ru. Точка и дефис могут присутвовать в доменном имени и названии почты
- Файлы logo.svg и cover.jpg, расположенные в репозитории не используются на странице (загружаются с серверов Яндекса). Просьба либо задействовать их либо удалить.
- Добавьте .gitignore, содержащий правила, исключающие попадание временных и\или системных файлов в репозиторий.

**Comment by i-c-winner** [comment]
Добрый день. Что то я не понимаю, ведь адреса http://ya.ru:00000, http://11.11.11.11:0000, https:yandex.ru и не проходят проверку...

**Comment by talantbekov123** [comment]
Ошибка на моей стороне, извиняюсь. Сейчас перепроверю все комментарии заново. @i-c-winner

**Comment by talantbekov123** [comment]
Все остальные комментарии, корректны.

**Comment by i-c-winner** [comment]
Остальные я подправил.

**Comment by talantbekov123** [comment]
Хорошая работа, выполнили все требования! Принимаю работу!
Прошу не забывать про комментарии **можно лучше**


**Можно лучше**
- Дополнительно включить в сет регулярки точки, подчеркивания. Не проходит валидная почты с использованием точки. Например: yandex.staff@gmail.com, alex.lion@gmail.com, test.test@test.gmail.com, best-email@yandex.ru. Точка и дефис могут присутвовать в доменном имени и названии почты
- Файлы logo.svg и cover.jpg, расположенные в репозитории не используются на странице (загружаются с серверов Яндекса). Просьба либо задействовать их либо удалить.
- Добавьте .gitignore, содержащий правила, исключающие попадание временных и\или системных файлов в репозиторий.

**Comment by i-c-winner** [comment]
Это я всегда делаю уже в режиме факультатива, если позволяет время
